name: keep Render server alive

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Ping the server
        run: |
          echo "Pinging the server at $SERVER_URL"
          python ping_server.py
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}

